"""initial schema

Revision ID: 4818d28a0750
Revises:
Create Date: 2026-04-16 19:47:08.890029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4818d28a0750"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_ref", sa.Text(), nullable=False),
        sa.Column("agent_definition_hash", sa.Text(), nullable=False),
        sa.Column("intake", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("final_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_uri", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'paused', 'completed', 'failed', 'cancelled')", name="ck_status"
        ),
        sa.CheckConstraint(
            "stop_reason IN ('done_node', 'policy_terminated', 'budget_exceeded', 'error', 'cancelled')",
            name="ck_stop_reason",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_runs_agent_ref", "runs", ["agent_ref"], unique=False)
    op.create_index("ix_runs_status_started_at", "runs", ["status", sa.literal_column("started_at DESC")], unique=False)
    op.create_table(
        "run_memory",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("node_name", sa.Text(), nullable=False),
        sa.Column("node_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_run_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("node_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'dispatched', 'in_progress', 'completed', 'failed')", name="ck_status"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "step_number", name="uq_steps_run_id_step_number"),
    )
    op.create_index("ix_steps_engine_run_id", "steps", ["engine_run_id"], unique=False)
    op.create_table(
        "policy_calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("available_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("selected_tool", sa.Text(), nullable=False),
        sa.Column("tool_arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("step_id"),
    )
    op.create_index("ix_policy_calls_run_id_created_at", "policy_calls", ["run_id", "created_at"], unique=False)
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("engine_run_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signature_ok", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('node_started', 'node_finished', 'node_failed', 'flow_terminated')", name="ck_event_type"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index("ix_webhook_events_run_id_received_at", "webhook_events", ["run_id", "received_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_webhook_events_run_id_received_at", table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index("ix_policy_calls_run_id_created_at", table_name="policy_calls")
    op.drop_table("policy_calls")
    op.drop_index("ix_steps_engine_run_id", table_name="steps")
    op.drop_table("steps")
    op.drop_table("run_memory")
    op.drop_index("ix_runs_status_started_at", table_name="runs")
    op.drop_index("ix_runs_agent_ref", table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
