"""add pending_aux_writes (FEAT-008)

Revision ID: 6bd53b01e704
Revises: 715ace057eb5
Create Date: 2026-04-21 19:52:21.628480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bd53b01e704'
down_revision: Union[str, None] = '715ace057eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_aux_writes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('signal_name', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    op.create_index('ix_pending_aux_writes_enqueued_at', 'pending_aux_writes', ['enqueued_at'], unique=False)
    op.create_index('ix_pending_aux_writes_entity_id', 'pending_aux_writes', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_aux_writes_entity_id', table_name='pending_aux_writes')
    op.drop_index('ix_pending_aux_writes_enqueued_at', table_name='pending_aux_writes')
    op.drop_table('pending_aux_writes')
    # ### end Alembic commands ###
