"""add github_check_id to task_implementations (FEAT-007)

Revision ID: 715ace057eb5
Revises: 0191383139ba
Create Date: 2026-04-21 16:01:17.355790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715ace057eb5'
down_revision: Union[str, None] = '0191383139ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_implementations', sa.Column('github_check_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_implementations', 'github_check_id')
    # ### end Alembic commands ###
